[package]
name = "snake-tui-rs"
version = "0.1.0"
edition = "2021"
description = "A TUI Snake Game"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.2"
rand = "0.8"
